data/record.c:12:13: error: [module2] __wti_module2_func1: Invalid access to private record 'S2' of [data]
data/record.c:12:13: error: [module2] __wti_module2_func1: Invalid access to private field 'S2 :: s' of [data]
data/record.c:29:5: error: [data] func: Invalid access to private name '__wti_module2_func1' of [module2]
data/record.c:30:5: error: [data] func: Invalid access to private name '__wti_module2_func1' of [module2]
data/record.c:35:10: error: [data] func: Invalid access to private name '__wti_module2_func1' of [module2]